image_folder: "./tmp"
workers: 4
batch_size: 192
batch_max_length: 25
imgH: 32
imgW: 100
rgb: False
character: "0123456789abcdefghijklmnopqrstuvwxyz"
PAD: False
num_fiducial: 20
input_channel: 1
output_channel: 512
hidden_size: 256

Transformation: "TPS"
FeatureExtraction: "ResNet"
SequenceModeling: "BiLSTM"
Prediction: "Attn"
sensitive: True
saved_model: "./inference/TPS-ResNet-BiLSTM-Attn-sensitive-v2.pth"
