[gcp]
type = "service_account"
project_id = "robotic-door-335106"
private_key_id = "eb1e5b4249db6a90f8fc03036674e51005000d08"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC00HygU/uF6OBI
6gFz5n8HkauANPnmTVmBvgwz/bD4+OTC1ZQT/OeNqnKeoP7C5W5bR0XoUQZWZTJa
ucVFaf++BCleGwwnYVu422KCPgJTwFpLwXFnvTbpyYxyA1+tCqeTKWCKblTKgyH8
/olUvwdEGPwcxZYn7dRo7kEdeVdQVQXMd7DKgqwu8xZxMkvtklm4A17CuBDWTrUV
atF4Vs8LHvYi9EVdfY3I92Kg8AaL6q5uCv0hEVrJPfFUZUSo92yS/BXUlTfqfgNJ
S8GW+QSop5wPStI97FmGEUB+1qnwDqPmrSKgxmG9v5bmwKBQwemSEKd8SxguVdBa
2GiU3d7zAgMBAAECggEARDsKVEvstZbvj8QyASThGZ+YGnyjMotMs99d5n6ceg8d
8AG9a597V2OS9hYlnLEMKEiocialIBP24PKKJQv/VBpo69iECRY9kO/EaAZzRVxo
Fn8sRqvJnYYPR/TK9Vb4bllmU0aYG4VJXZlFhGPDn6hX9pl+9JlUFraVfsRLtQWD
7ynh4rfowhJDcUSf8rDK49orG+eyfJALt++1SL+o8O2hFiaHT22ZxY2GRZW2vDrS
CRPUXRqBiHwmQm68z4rQwaAj4c1V9uUyTpwU1O5CspyFE1iOh+uR3CrodWhzkZ96
Nh8sVUWFRYH44Al5zBbKPV8wYcYEgW5lpxbCsPiAyQKBgQD9Lpmhwbuss2wuzcZH
x4f/NLAfrEqi540VJ6+cr2DdskCX1mGvj3h7Xg7EF2O85MP7PDmMMGlLWagxTR81
sdUI+UeLTVIySnPtpYDfroQXchXL02KwFNvbpgsYw7+c5zN700w588hij0oUfM8+
FNwoHnVCaafoW0OhQnIXKQujWwKBgQC206/ueOm+Syiwj/nMuREXdDIbMVVPtAwG
G/+bcoU08S5i0I8yCAqY/es8IPdN5yDrya1nGK1VQJTouuJWzXEmtoUcLQOu2b4f
WgNArT1RCO1bE3uBT/2Tkc9Q+9sO+tw5dyCu05L1/oC0tPpa54VRHU0mUmTYvgWn
ChGc/uj+SQKBgAtQttsM3odkaXRaC/+PQlu8jhaMS7WmJZ8JbAbTq7+cxNhEY49G
GTtiQ8Styu5ZRw0Gbwf97ebJNgQmDzwGG6BQC8uFBCRtQWsgl3bnxM2Lcr/uTZ3T
ANR7Qkm0De9EQf/JvMFmTNFi2Au8XELJCeHdIp56PF/dHFOrtY+lbPi7AoGBAJPx
KGQoo7zAxORbHSB0gUghVop6mTYt06z96xC20uPMZmS/r6Aksa6rijbV1kjLxvAF
+rN6XIioAddxosXq6K0S9ROfuWM7/4UPKaKkjQGN38PbOA2j1OYdD03Q/6pXhO1b
YK8XtcwpbazM5em5fz/sHgnskn5xBdHta+NGwvNBAoGAU3Y9ZvWxxdkWQu7iz2W6
1kdR7RQ9fAddj0L6NEbW7EIQyEOllQhxN0SO+RxvDgXrySihbDavzHtXfEMo2gxX
K0TzeSH55IqMTh8l/zLw59jIfABf+v5V1AVDtgXdZq28aposUMHNyADYPGdZjhbb
2uP+fAYLxIGAsnAd2hoGBV4=
-----END PRIVATE KEY-----
"""
client_email = "477915629025-compute@developer.gserviceaccount.com"
client_id = "109638312599230254506"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/477915629025-compute%40developer.gserviceaccount.com"
bucket = "cv18-bucket"
X-Naver-Client-Id = "JdmToa1Zg9kJdl0rseNx"
X-Naver-Client-Secret = "FI01lx3L7e"